// <auto-generated />
using System;
using ChemistryCafeAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChemistryCafeAPI.Migrations
{
    [DbContext(typeof(ChemistryDbContext))]
    [Migration("20260825205855_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ChemistryCafeAPI.Models.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("ChemistryCafeAPI.Models.Mechanism", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.ToTable("Mechanisms");
                });

            modelBuilder.Entity("ChemistryCafeAPI.Models.MechanismPhase", b =>
                {
                    b.Property<Guid>("MechanismId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PhaseId")
                        .HasColumnType("char(36)");

                    b.HasKey("MechanismId", "PhaseId");

                    b.HasIndex("PhaseId");

                    b.ToTable("MechanismPhase");
                });

            modelBuilder.Entity("ChemistryCafeAPI.Models.MechanismReaction", b =>
                {
                    b.Property<Guid>("MechanismId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ReactionId")
                        .HasColumnType("char(36)");

                    b.HasKey("MechanismId", "ReactionId");

                    b.HasIndex("ReactionId");

                    b.ToTable("MechanismReaction");
                });

            modelBuilder.Entity("ChemistryCafeAPI.Models.MechanismSpecies", b =>
                {
                    b.Property<Guid>("MechanismId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("char(36)");

                    b.HasKey("MechanismId", "SpeciesId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("MechanismSpecies");
                });

            modelBuilder.Entity("ChemistryCafeAPI.Models.Phase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.ToTable("Phases");
                });

            modelBuilder.Entity("ChemistryCafeAPI.Models.Product", b =>
                {
                    b.Property<Guid>("ReactionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Branch")
                        .HasColumnType("longtext");

                    b.Property<double>("Coefficient")
                        .HasColumnType("double");

                    b.HasKey("ReactionId", "SpeciesId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ChemistryCafeAPI.Models.Reactant", b =>
                {
                    b.Property<Guid>("ReactionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("char(36)");

                    b.Property<double>("Coefficient")
                        .HasColumnType("double");

                    b.HasKey("ReactionId", "SpeciesId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Reactants");
                });

            modelBuilder.Entity("ChemistryCafeAPI.Models.Reaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AerosolPhaseId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AerosolPhaseSpeciesId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AerosolPhaseWaterId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("GasPhaseId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("GasPhaseSpeciesId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReactionType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AerosolPhaseId");

                    b.HasIndex("AerosolPhaseSpeciesId");

                    b.HasIndex("AerosolPhaseWaterId");

                    b.HasIndex("FamilyId");

                    b.HasIndex("GasPhaseId");

                    b.HasIndex("GasPhaseSpeciesId");

                    b.ToTable("Reactions");
                });

            modelBuilder.Entity("ChemistryCafeAPI.Models.ReactionNumericalAttribute", b =>
                {
                    b.Property<Guid>("ReactionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SerializationKey")
                        .HasColumnType("varchar(255)");

                    b.Property<double>("Value")
                        .HasColumnType("double");

                    b.HasKey("ReactionId", "SerializationKey");

                    b.ToTable("ReactionNumericalAttributes");
                });

            modelBuilder.Entity("ChemistryCafeAPI.Models.ReactionStringAttribute", b =>
                {
                    b.Property<Guid>("ReactionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SerializationKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ReactionId", "SerializationKey");

                    b.ToTable("ReactionStringAttributes");
                });

            modelBuilder.Entity("ChemistryCafeAPI.Models.Species", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double?>("AbsoluteTolerance")
                        .HasColumnType("double");

                    b.Property<double?>("ConstantConcentration")
                        .HasColumnType("double");

                    b.Property<double?>("ConstantMixingRatio")
                        .HasColumnType("double");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("char(36)");

                    b.Property<bool?>("IsThirdBody")
                        .HasColumnType("tinyint(1)");

                    b.Property<double?>("MolecularWeight")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OtherProperties")
                        .HasColumnType("json");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.ToTable("Species");
                });

            modelBuilder.Entity("ChemistryCafeAPI.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("GoogleId")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Username" }, "idx_users_username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PhaseSpecies", b =>
                {
                    b.Property<Guid>("PhasesId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("char(36)");

                    b.HasKey("PhasesId", "SpeciesId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("PhaseSpecies");
                });

            modelBuilder.Entity("ChemistryCafeAPI.Models.Family", b =>
                {
                    b.HasOne("ChemistryCafeAPI.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ChemistryCafeAPI.Models.Mechanism", b =>
                {
                    b.HasOne("ChemistryCafeAPI.Models.Family", "Family")
                        .WithMany("Mechanisms")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");
                });

            modelBuilder.Entity("ChemistryCafeAPI.Models.MechanismPhase", b =>
                {
                    b.HasOne("ChemistryCafeAPI.Models.Mechanism", null)
                        .WithMany()
                        .HasForeignKey("MechanismId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChemistryCafeAPI.Models.Phase", null)
                        .WithMany()
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChemistryCafeAPI.Models.MechanismReaction", b =>
                {
                    b.HasOne("ChemistryCafeAPI.Models.Mechanism", null)
                        .WithMany()
                        .HasForeignKey("MechanismId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChemistryCafeAPI.Models.Reaction", null)
                        .WithMany()
                        .HasForeignKey("ReactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChemistryCafeAPI.Models.MechanismSpecies", b =>
                {
                    b.HasOne("ChemistryCafeAPI.Models.Mechanism", null)
                        .WithMany()
                        .HasForeignKey("MechanismId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChemistryCafeAPI.Models.Species", null)
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChemistryCafeAPI.Models.Phase", b =>
                {
                    b.HasOne("ChemistryCafeAPI.Models.Family", "Family")
                        .WithMany("Phases")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");
                });

            modelBuilder.Entity("ChemistryCafeAPI.Models.Product", b =>
                {
                    b.HasOne("ChemistryCafeAPI.Models.Reaction", "Reaction")
                        .WithMany("Products")
                        .HasForeignKey("ReactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChemistryCafeAPI.Models.Species", "Species")
                        .WithMany("AsProduct")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reaction");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("ChemistryCafeAPI.Models.Reactant", b =>
                {
                    b.HasOne("ChemistryCafeAPI.Models.Reaction", "Reaction")
                        .WithMany("Reactants")
                        .HasForeignKey("ReactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChemistryCafeAPI.Models.Species", "Species")
                        .WithMany("AsReactant")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reaction");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("ChemistryCafeAPI.Models.Reaction", b =>
                {
                    b.HasOne("ChemistryCafeAPI.Models.Phase", "AerosolPhase")
                        .WithMany("AsAerosolPhase")
                        .HasForeignKey("AerosolPhaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ChemistryCafeAPI.Models.Species", "AerosolPhaseSpecies")
                        .WithMany("AsAerosolPhaseSpecies")
                        .HasForeignKey("AerosolPhaseSpeciesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ChemistryCafeAPI.Models.Species", "AerosolPhaseWater")
                        .WithMany("AsAerosolPhaseWater")
                        .HasForeignKey("AerosolPhaseWaterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ChemistryCafeAPI.Models.Family", "Family")
                        .WithMany("Reactions")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChemistryCafeAPI.Models.Phase", "GasPhase")
                        .WithMany("AsGasPhase")
                        .HasForeignKey("GasPhaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ChemistryCafeAPI.Models.Species", "GasPhaseSpecies")
                        .WithMany("AsGasPhaseSpecies")
                        .HasForeignKey("GasPhaseSpeciesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AerosolPhase");

                    b.Navigation("AerosolPhaseSpecies");

                    b.Navigation("AerosolPhaseWater");

                    b.Navigation("Family");

                    b.Navigation("GasPhase");

                    b.Navigation("GasPhaseSpecies");
                });

            modelBuilder.Entity("ChemistryCafeAPI.Models.ReactionNumericalAttribute", b =>
                {
                    b.HasOne("ChemistryCafeAPI.Models.Reaction", "Reaction")
                        .WithMany("NumericalAttributes")
                        .HasForeignKey("ReactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reaction");
                });

            modelBuilder.Entity("ChemistryCafeAPI.Models.ReactionStringAttribute", b =>
                {
                    b.HasOne("ChemistryCafeAPI.Models.Reaction", "Reaction")
                        .WithMany("StringAttributes")
                        .HasForeignKey("ReactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reaction");
                });

            modelBuilder.Entity("ChemistryCafeAPI.Models.Species", b =>
                {
                    b.HasOne("ChemistryCafeAPI.Models.Family", "Family")
                        .WithMany("Species")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");
                });

            modelBuilder.Entity("PhaseSpecies", b =>
                {
                    b.HasOne("ChemistryCafeAPI.Models.Phase", null)
                        .WithMany()
                        .HasForeignKey("PhasesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChemistryCafeAPI.Models.Species", null)
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChemistryCafeAPI.Models.Family", b =>
                {
                    b.Navigation("Mechanisms");

                    b.Navigation("Phases");

                    b.Navigation("Reactions");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("ChemistryCafeAPI.Models.Phase", b =>
                {
                    b.Navigation("AsAerosolPhase");

                    b.Navigation("AsGasPhase");
                });

            modelBuilder.Entity("ChemistryCafeAPI.Models.Reaction", b =>
                {
                    b.Navigation("NumericalAttributes");

                    b.Navigation("Products");

                    b.Navigation("Reactants");

                    b.Navigation("StringAttributes");
                });

            modelBuilder.Entity("ChemistryCafeAPI.Models.Species", b =>
                {
                    b.Navigation("AsAerosolPhaseSpecies");

                    b.Navigation("AsAerosolPhaseWater");

                    b.Navigation("AsGasPhaseSpecies");

                    b.Navigation("AsProduct");

                    b.Navigation("AsReactant");
                });
#pragma warning restore 612, 618
        }
    }
}
