name: .NET Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    # Check out the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up .NET with version 6.0.x
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    # Restore the dependencies of the .NET project
    - name: Restore dependencies
      run: dotnet restore ./backend

    # Build the project
    - name: Build
      run: dotnet build ./backend --no-restore


    # Start database container
    - name: Start database container
      run: docker compose up -d mysql

    # Wait for the database to be ready
    - name: Wait for database to be ready
      run: |
        until docker exec mysql mysqladmin ping -h"localhost" --silent; do
          echo "Waiting for database connection..."
          sleep 2
        done

    # Run tests
    - name: Test
      run: dotnet test ./backend --no-build --verbosity normal

    # Stop and clean up containers
    - name: Stop and remove database container
      run: docker compose down