name: .NET Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:9.0
        env:
          MYSQL_SERVER: mysql
          MYSQL_USER: chemistrycafedev
          MYSQL_PASSWORD: chemistrycafe
          MYSQL_DATABASE: chemistry_db
        ports:
          - "3306:3306"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./backend

      - name: Build
        run: dotnet build ./backend --no-restore
      
      - name: Install entity framework
        run: dotnet tool install --global dotnet-ef

      - name: Migrate Database
        env:
          MYSQL_SERVER: "127.0.0.1"
          MYSQL_USER: chemistrycafedev
          MYSQL_PASSWORD: chemistrycafe
          MYSQL_DATABASE: chemistry_db
        run: dotnet ef database update --project .\backend\ChemistryCafeAPI.csproj

      - name: Test
        env:
          MYSQL_SERVER: "127.0.0.1"
          MYSQL_USER: chemistrycafedev
          MYSQL_PASSWORD: chemistrycafe
          MYSQL_DATABASE: chemistry_db
        run: dotnet test ./backend --collect "Code Coverage;Format=Cobertura" --no-build --verbosity normal --environment MYSQL_SERVER="127.0.0.1" --environment MYSQL_USER="chemistrycafedev" --environment MYSQL_PASSWORD="chemistrycafe" --environment MYSQL_DATABASE="chemistry_db"

      - name: Stop and remove database container
        run: docker compose down
